pipeline {
 agent any
 stages {
   stage('Maven Install') {
     steps {
       bat 'mvn clean package'
     }
   }
   stage('Docker Build') {
    steps {
      bat 'docker build -t vanseverk/cafeserviceapplication:latest .'
    }
  }
  stage('Docker Push') {
    steps {
      withCredentials([usernamePassword(credentialsId: 'dockerhub', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
        bat 'docker login --username %USERNAME% --password %PASSWORD%'
      }

      bat 'docker push vanseverk/cafeserviceapplication:latest'
    }
  }
  stage('Kubernetes Deploy') {
    steps {
      bat 'kubectl run cafeserviceapplication --namespace=monitoring --image=vanseverk/cafeserviceapplication:latest --port=8080'
    }
  }
 }
}


